import type { IngredientData } from '@/types'

/**
 * Philippine pet ingredient library — values per 100 g cooked / as-fed.
 * Data sourced from USDA FoodData Central + Philippine Food Composition Tables.
 */
export const INGREDIENTS: IngredientData[] = [
  // ── PROTEINS ──────────────────────────────────────────────────────────────
  {
    id: 'chicken_breast',
    name: 'Chicken Breast (cooked)',
    category: 'protein',
    kcal: 165, protein_g: 31.0, fat_g: 3.6, carbs_g: 0, fiber_g: 0,
    calcium_mg: 15, phosphorus_mg: 220, iron_mg: 1.0, zinc_mg: 1.0,
    vitamin_a_iu: 18, vitamin_d_iu: 5, taurine_mg: 60, omega3_mg: 30,
    isPhIngredient: true,
  },
  {
    id: 'chicken_thigh',
    name: 'Chicken Thigh (cooked, boneless)',
    category: 'protein',
    kcal: 209, protein_g: 26.2, fat_g: 11.0, carbs_g: 0, fiber_g: 0,
    calcium_mg: 11, phosphorus_mg: 179, iron_mg: 1.2, zinc_mg: 2.4,
    vitamin_a_iu: 48, vitamin_d_iu: 4, taurine_mg: 80, omega3_mg: 120,
    isPhIngredient: true,
  },
  {
    id: 'beef_lean',
    name: 'Beef, Lean (cooked)',
    category: 'protein',
    kcal: 215, protein_g: 26.0, fat_g: 11.0, carbs_g: 0, fiber_g: 0,
    calcium_mg: 19, phosphorus_mg: 196, iron_mg: 2.5, zinc_mg: 5.0,
    vitamin_a_iu: 0, vitamin_d_iu: 1, taurine_mg: 50, omega3_mg: 60,
    isPhIngredient: true,
  },
  {
    id: 'pork_lean',
    name: 'Pork, Lean (cooked)',
    category: 'protein',
    kcal: 242, protein_g: 27.0, fat_g: 14.0, carbs_g: 0, fiber_g: 0,
    calcium_mg: 19, phosphorus_mg: 246, iron_mg: 1.5, zinc_mg: 2.5,
    vitamin_a_iu: 0, vitamin_d_iu: 1, taurine_mg: 50, omega3_mg: 40,
    notes: 'Must be fully cooked. Avoid raw or undercooked pork.',
    isPhIngredient: true,
  },

  // ── ORGANS ────────────────────────────────────────────────────────────────
  {
    id: 'chicken_liver',
    name: 'Chicken Liver (cooked)',
    category: 'organ',
    kcal: 167, protein_g: 24.5, fat_g: 6.5, carbs_g: 0.9, fiber_g: 0,
    calcium_mg: 13, phosphorus_mg: 297, iron_mg: 9.0, zinc_mg: 4.0,
    vitamin_a_iu: 13000, vitamin_d_iu: 50, taurine_mg: 120, omega3_mg: 40,
    notes: 'Rich in Vitamin A — keep to ≤10% of diet to avoid toxicity.',
    isPhIngredient: true,
  },
  {
    id: 'chicken_gizzard',
    name: 'Chicken Gizzard (cooked)',
    category: 'organ',
    kcal: 154, protein_g: 26.2, fat_g: 4.6, carbs_g: 0.0, fiber_g: 0,
    calcium_mg: 15, phosphorus_mg: 176, iron_mg: 3.5, zinc_mg: 3.9,
    vitamin_a_iu: 35, vitamin_d_iu: 5, taurine_mg: 130, omega3_mg: 25,
    isPhIngredient: true,
  },
  {
    id: 'beef_liver',
    name: 'Beef Liver (cooked)',
    category: 'organ',
    kcal: 191, protein_g: 23.1, fat_g: 5.3, carbs_g: 4.0, fiber_g: 0,
    calcium_mg: 11, phosphorus_mg: 387, iron_mg: 5.8, zinc_mg: 4.0,
    vitamin_a_iu: 26000, vitamin_d_iu: 40, taurine_mg: 68, omega3_mg: 35,
    notes: 'Very high in Vitamin A — keep to ≤5% of diet, especially for cats.',
    isPhIngredient: true,
  },
  {
    id: 'chicken_heart',
    name: 'Chicken Heart (cooked)',
    category: 'organ',
    kcal: 185, protein_g: 26.4, fat_g: 8.1, carbs_g: 0.1, fiber_g: 0,
    calcium_mg: 11, phosphorus_mg: 215, iron_mg: 5.9, zinc_mg: 6.6,
    vitamin_a_iu: 10, vitamin_d_iu: 10, taurine_mg: 700, omega3_mg: 200,
    notes: 'Excellent taurine source — especially important for cats.',
    isPhIngredient: true,
  },

  // ── FISH ──────────────────────────────────────────────────────────────────
  {
    id: 'tilapia',
    name: 'Tilapia (cooked)',
    category: 'fish',
    kcal: 128, protein_g: 26.2, fat_g: 2.7, carbs_g: 0, fiber_g: 0,
    calcium_mg: 10, phosphorus_mg: 204, iron_mg: 0.5, zinc_mg: 0.5,
    vitamin_a_iu: 0, vitamin_d_iu: 5, taurine_mg: 90, omega3_mg: 200,
    isPhIngredient: true,
  },
  {
    id: 'bangus',
    name: 'Bangus / Milkfish (cooked, boneless)',
    category: 'fish',
    kcal: 148, protein_g: 23.0, fat_g: 5.6, carbs_g: 0, fiber_g: 0,
    calcium_mg: 66, phosphorus_mg: 196, iron_mg: 1.4, zinc_mg: 0.9,
    vitamin_a_iu: 36, vitamin_d_iu: 10, taurine_mg: 70, omega3_mg: 400,
    notes: 'Remove all bones. Rich in calcium.',
    isPhIngredient: true,
  },
  {
    id: 'tuna_water',
    name: 'Tuna, Canned in Water',
    category: 'fish',
    kcal: 116, protein_g: 25.5, fat_g: 1.0, carbs_g: 0, fiber_g: 0,
    calcium_mg: 17, phosphorus_mg: 298, iron_mg: 1.4, zinc_mg: 0.7,
    vitamin_a_iu: 10, vitamin_d_iu: 4, taurine_mg: 300, omega3_mg: 250,
    notes: 'Limit to occasional use in cats — can cause nutritional imbalances.',
    isPhIngredient: true,
  },
  {
    id: 'sardines_water',
    name: 'Sardines, Canned in Water',
    category: 'fish',
    kcal: 208, protein_g: 24.6, fat_g: 11.5, carbs_g: 0, fiber_g: 0,
    calcium_mg: 382, phosphorus_mg: 490, iron_mg: 2.9, zinc_mg: 1.5,
    vitamin_a_iu: 54, vitamin_d_iu: 193, taurine_mg: 200, omega3_mg: 1480,
    notes: 'Excellent calcium + omega-3 source. Choose water-packed, no salt added.',
    isPhIngredient: true,
  },
  {
    id: 'salmon',
    name: 'Salmon (cooked)',
    category: 'fish',
    kcal: 208, protein_g: 20.0, fat_g: 13.0, carbs_g: 0, fiber_g: 0,
    calcium_mg: 13, phosphorus_mg: 289, iron_mg: 0.5, zinc_mg: 0.6,
    vitamin_a_iu: 50, vitamin_d_iu: 447, taurine_mg: 130, omega3_mg: 2260,
    notes: 'Must be fully cooked. Never feed raw salmon (can carry harmful parasites).',
    isPhIngredient: true,
  },

  // ── EGGS ──────────────────────────────────────────────────────────────────
  {
    id: 'egg_whole',
    name: 'Egg, Whole (cooked)',
    category: 'egg',
    kcal: 155, protein_g: 12.6, fat_g: 10.6, carbs_g: 1.1, fiber_g: 0,
    calcium_mg: 50, phosphorus_mg: 172, iron_mg: 1.2, zinc_mg: 1.1,
    vitamin_a_iu: 520, vitamin_d_iu: 87, taurine_mg: 12, omega3_mg: 100,
    notes: 'Always cook eggs. Raw egg whites block biotin absorption.',
    isPhIngredient: true,
  },
  {
    id: 'egg_white',
    name: 'Egg White (cooked)',
    category: 'egg',
    kcal: 52, protein_g: 10.9, fat_g: 0.2, carbs_g: 0.7, fiber_g: 0,
    calcium_mg: 7, phosphorus_mg: 15, iron_mg: 0.1, zinc_mg: 0.03,
    vitamin_a_iu: 0, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 0,
    notes: 'Must be cooked. Raw egg whites destroy biotin.',
    isPhIngredient: true,
  },

  // ── VEGETABLES ────────────────────────────────────────────────────────────
  {
    id: 'sweet_potato',
    name: 'Sweet Potato / Kamote (cooked)',
    category: 'vegetable',
    kcal: 90, protein_g: 2.0, fat_g: 0.1, carbs_g: 20.7, fiber_g: 3.3,
    calcium_mg: 27, phosphorus_mg: 47, iron_mg: 0.6, zinc_mg: 0.3,
    vitamin_a_iu: 11510, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 15,
    isPhIngredient: true,
  },
  {
    id: 'carrot',
    name: 'Carrots (cooked)',
    category: 'vegetable',
    kcal: 35, protein_g: 0.8, fat_g: 0.2, carbs_g: 8.2, fiber_g: 3.0,
    calcium_mg: 30, phosphorus_mg: 30, iron_mg: 0.3, zinc_mg: 0.2,
    vitamin_a_iu: 16700, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 5,
    isPhIngredient: true,
  },
  {
    id: 'squash',
    name: 'Squash / Kalabasa (cooked)',
    category: 'vegetable',
    kcal: 34, protein_g: 0.9, fat_g: 0.3, carbs_g: 7.5, fiber_g: 1.5,
    calcium_mg: 14, phosphorus_mg: 25, iron_mg: 0.5, zinc_mg: 0.3,
    vitamin_a_iu: 2090, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 50,
    isPhIngredient: true,
  },
  {
    id: 'broccoli',
    name: 'Broccoli (cooked)',
    category: 'vegetable',
    kcal: 35, protein_g: 2.4, fat_g: 0.4, carbs_g: 7.2, fiber_g: 3.3,
    calcium_mg: 40, phosphorus_mg: 67, iron_mg: 0.7, zinc_mg: 0.5,
    vitamin_a_iu: 623, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 80,
    isPhIngredient: true,
  },
  {
    id: 'spinach',
    name: 'Spinach (cooked)',
    category: 'vegetable',
    kcal: 23, protein_g: 3.0, fat_g: 0.3, carbs_g: 3.8, fiber_g: 2.4,
    calcium_mg: 136, phosphorus_mg: 56, iron_mg: 3.6, zinc_mg: 0.8,
    vitamin_a_iu: 9380, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 140,
    notes: 'High in oxalates. Limit in pets with kidney or bladder issues.',
    isPhIngredient: true,
  },
  {
    id: 'kangkong',
    name: 'Kangkong / Water Spinach (cooked)',
    category: 'vegetable',
    kcal: 22, protein_g: 2.5, fat_g: 0.2, carbs_g: 3.7, fiber_g: 2.1,
    calcium_mg: 48, phosphorus_mg: 34, iron_mg: 2.0, zinc_mg: 0.4,
    vitamin_a_iu: 6350, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 30,
    isPhIngredient: true,
  },
  {
    id: 'green_beans',
    name: 'Green Beans / Sitaw (cooked)',
    category: 'vegetable',
    kcal: 31, protein_g: 1.8, fat_g: 0.2, carbs_g: 7.1, fiber_g: 3.4,
    calcium_mg: 37, phosphorus_mg: 38, iron_mg: 1.0, zinc_mg: 0.2,
    vitamin_a_iu: 690, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 60,
    isPhIngredient: true,
  },
  {
    id: 'zucchini',
    name: 'Zucchini / Upo (cooked)',
    category: 'vegetable',
    kcal: 17, protein_g: 1.2, fat_g: 0.3, carbs_g: 3.1, fiber_g: 1.0,
    calcium_mg: 16, phosphorus_mg: 38, iron_mg: 0.4, zinc_mg: 0.3,
    vitamin_a_iu: 200, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 90,
    isPhIngredient: true,
  },

  // ── GRAINS ────────────────────────────────────────────────────────────────
  {
    id: 'brown_rice',
    name: 'Brown Rice (cooked)',
    category: 'grain',
    kcal: 111, protein_g: 2.6, fat_g: 0.9, carbs_g: 22.8, fiber_g: 1.8,
    calcium_mg: 10, phosphorus_mg: 83, iron_mg: 0.4, zinc_mg: 0.6,
    vitamin_a_iu: 0, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 12,
    isPhIngredient: true,
  },
  {
    id: 'white_rice',
    name: 'White Rice (cooked)',
    category: 'grain',
    kcal: 130, protein_g: 2.7, fat_g: 0.3, carbs_g: 28.2, fiber_g: 0.4,
    calcium_mg: 10, phosphorus_mg: 43, iron_mg: 0.2, zinc_mg: 0.5,
    vitamin_a_iu: 0, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 2,
    isPhIngredient: true,
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal (cooked)',
    category: 'grain',
    kcal: 71, protein_g: 2.5, fat_g: 1.4, carbs_g: 12.0, fiber_g: 1.7,
    calcium_mg: 11, phosphorus_mg: 95, iron_mg: 1.0, zinc_mg: 1.0,
    vitamin_a_iu: 0, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 25,
    isPhIngredient: true,
  },

  // ── FRUITS ────────────────────────────────────────────────────────────────
  {
    id: 'apple',
    name: 'Apple (peeled, no seeds)',
    category: 'fruit',
    kcal: 52, protein_g: 0.3, fat_g: 0.2, carbs_g: 13.8, fiber_g: 2.4,
    calcium_mg: 6, phosphorus_mg: 11, iron_mg: 0.1, zinc_mg: 0.04,
    vitamin_a_iu: 54, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 9,
    notes: 'Remove core and seeds — apple seeds contain cyanide.',
    isPhIngredient: true,
  },
  {
    id: 'banana',
    name: 'Banana / Saging (ripe)',
    category: 'fruit',
    kcal: 89, protein_g: 1.1, fat_g: 0.3, carbs_g: 22.8, fiber_g: 2.6,
    calcium_mg: 5, phosphorus_mg: 22, iron_mg: 0.3, zinc_mg: 0.15,
    vitamin_a_iu: 64, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 27,
    notes: 'High in sugar. Use as treat only.',
    isPhIngredient: true,
  },
  {
    id: 'blueberry',
    name: 'Blueberries',
    category: 'fruit',
    kcal: 57, protein_g: 0.7, fat_g: 0.3, carbs_g: 14.5, fiber_g: 2.4,
    calcium_mg: 6, phosphorus_mg: 12, iron_mg: 0.3, zinc_mg: 0.2,
    vitamin_a_iu: 54, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 58,
    isPhIngredient: false,
  },

  // ── FATS ──────────────────────────────────────────────────────────────────
  {
    id: 'coconut_oil',
    name: 'Coconut Oil (VCO)',
    category: 'fat',
    kcal: 862, protein_g: 0, fat_g: 100, carbs_g: 0, fiber_g: 0,
    calcium_mg: 0, phosphorus_mg: 0, iron_mg: 0, zinc_mg: 0,
    vitamin_a_iu: 0, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 0,
    notes: 'Use sparingly. Max ¼ tsp per 5 kg body weight per day.',
    isPhIngredient: true,
  },
  {
    id: 'olive_oil',
    name: 'Olive Oil',
    category: 'fat',
    kcal: 884, protein_g: 0, fat_g: 100, carbs_g: 0, fiber_g: 0,
    calcium_mg: 1, phosphorus_mg: 0, iron_mg: 0.6, zinc_mg: 0,
    vitamin_a_iu: 0, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 761,
    isPhIngredient: false,
  },
  {
    id: 'salmon_oil',
    name: 'Salmon / Fish Oil',
    category: 'fat',
    kcal: 884, protein_g: 0, fat_g: 100, carbs_g: 0, fiber_g: 0,
    calcium_mg: 0, phosphorus_mg: 0, iron_mg: 0, zinc_mg: 0,
    vitamin_a_iu: 730, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 35000,
    notes: 'Excellent EPA/DHA source. Use ¼ tsp per 5 kg body weight per day.',
    isPhIngredient: false,
  },

  // ── SUPPLEMENTS ───────────────────────────────────────────────────────────
  {
    id: 'eggshell_powder',
    name: 'Eggshell Powder',
    category: 'supplement',
    kcal: 0, protein_g: 0, fat_g: 0, carbs_g: 0, fiber_g: 0,
    calcium_mg: 2300, phosphorus_mg: 0, iron_mg: 0, zinc_mg: 0,
    vitamin_a_iu: 0, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 0,
    notes: 'Dry and grind clean eggshells. ~1 tsp ≈ 2,300 mg calcium.',
    isPhIngredient: true,
  },
  {
    id: 'bone_meal',
    name: 'Bone Meal (sterilized)',
    category: 'supplement',
    kcal: 150, protein_g: 20, fat_g: 5, carbs_g: 0, fiber_g: 0,
    calcium_mg: 3000, phosphorus_mg: 1500, iron_mg: 0, zinc_mg: 0,
    vitamin_a_iu: 0, vitamin_d_iu: 0, taurine_mg: 0, omega3_mg: 0,
    notes: 'Use sterilized/food-grade bone meal only. Provides Ca:P at 2:1 ratio.',
    isPhIngredient: false,
  },
]

/** Look up an ingredient by id (O(n) — small dataset) */
export function getIngredientById(id: string): IngredientData | undefined {
  return INGREDIENTS.find(i => i.id === id)
}

/** Category display labels */
export const CATEGORY_LABEL: Record<string, string> = {
  protein: 'Protein',
  organ: 'Organ Meat',
  fish: 'Fish & Seafood',
  egg: 'Eggs',
  vegetable: 'Vegetables',
  grain: 'Grains',
  fruit: 'Fruits',
  fat: 'Fats & Oils',
  supplement: 'Supplements',
}

export const CATEGORY_ORDER = [
  'protein', 'organ', 'fish', 'egg',
  'vegetable', 'grain', 'fruit', 'fat', 'supplement',
]
